const mongoose = require("mongoose");
const requireLogin = require("../middlewares/requireLogin");
const requireCredits = require("../middlewares/requireCredits");

// Avoid test?
const Survey = mongoose.model("surveys");

module.exports = app => {
	// As many middleware is possible, but sequence matters
	// Check for login before check for credits
	app.post("/api/surveys", requireLogin, requireCredits, (req, res) => {
		const { title, subject, body, recipients } = req.body;

		const survey = new Survey({
			title,
			subject,
			body,
			recipients: recipients.split(",").map(email => ({ email: email.trim() })),
			_user: req.user.id, //id is auto generated by mongo
			dateSent: Date.now()
		});
	});
};
